# Generated by Django 4.0 on 2023-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('works_at', models.TextField()),
                ('locat', models.CharField(max_length=100)),
                ('explist', models.TextField()),
                ('about', models.TextField()),
                ('eduction', models.TextField()),
            ],
        ),
    ]
