# Generated by Django 4.0 on 2023-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('works_at', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('exp', models.TextField()),
                ('about', models.TextField()),
                ('uname', models.CharField(max_length=255)),
                ('education', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
