# Generated by Django 4.2.5 on 2023-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0002_scrapeddata_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=250)),
                ('industry', models.TextField()),
                ('company_size', models.TextField()),
                ('headquarter', models.TextField()),
                ('founded', models.CharField(max_length=255)),
                ('foll', models.CharField(max_length=255)),
                ('specialties', models.TextField()),
            ],
        ),
    ]
