# Generated by Django 4.2.5 on 2023-09-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0004_employeedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='e_head',
            new_name='emp_info',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='e_link',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='e_name',
        ),
    ]
