# Generated by Django 4.2.5 on 2023-09-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0005_rename_e_head_employeedetails_emp_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
