# Generated by Django 4.2.5 on 2023-09-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0011_employeedetail1_delete_employeedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail1',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Linkapp.companydata1'),
        ),
    ]
