# Generated by Django 4.2.5 on 2023-09-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0012_alter_employeedetail1_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('e_name', models.CharField(max_length=255)),
                ('e_head', models.TextField()),
                ('e_link', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CompanyData1',
            new_name='CompanyData2',
        ),
        migrations.DeleteModel(
            name='EmployeeDetail1',
        ),
        migrations.AddField(
            model_name='employeedetail2',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Linkapp.companydata2'),
        ),
    ]
