# Generated by Django 4.2.5 on 2023-09-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0015_employeedetail_rename_companydata3_companydata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Linkapp.companydata'),
        ),
    ]
