# Generated by Django 4.2.5 on 2023-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0017_rename_companydata_companydata1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=250)),
                ('industry', models.TextField()),
                ('company_size', models.TextField()),
                ('headquarter', models.TextField()),
                ('founded', models.CharField(max_length=255)),
                ('foll', models.CharField(max_length=255)),
                ('specialties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=255)),
                ('e_head', models.TextField()),
                ('e_link', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetail1',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyData1',
        ),
        migrations.DeleteModel(
            name='EmployeeDetail1',
        ),
    ]
