# Generated by Django 4.2.5 on 2023-10-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0018_companydata_employeedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData1',
            fields=[
                ('comp_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('website', models.URLField(max_length=250)),
                ('industry', models.TextField()),
                ('company_size', models.TextField()),
                ('headquarter', models.TextField()),
                ('founded', models.CharField(max_length=255)),
                ('foll', models.CharField(max_length=255)),
                ('specialties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=255)),
                ('e_head', models.TextField()),
                ('e_link', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Linkapp.companydata1')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyData',
        ),
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
    ]
