# Generated by Django 4.2.5 on 2023-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkapp', '0019_companydata1_employeedetail1_delete_companydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(max_length=250)),
                ('name', models.CharField(max_length=255)),
                ('works_at', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('exp', models.TextField()),
                ('about', models.TextField()),
                ('uname', models.CharField(max_length=255)),
                ('education', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
